GET http://localhost:4000/post

###

GET http://localhost:4000/post/all

###

POST http://localhost:4000/post
Content-Type: application/json

{

    "title": "Cat needs new home",
    "text": "Found on the street"
}

###

PUT http://localhost:4000/post/6267f6b60a16df84157a96ec
Content-Type: application/json

{
    "username": "CoolKid",
    "title": "Cat loves milk",
    "description": "If you love your cat let it drink milk!",
    "_id": "6267f6b60a16df84157a96ec"
}

###

DELETE http://localhost:4000/post/626154de440464adb9603c4d