GET http://localhost:3000/post

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "username": "Anna",
    "title": "Cat needs new home",
    "description": "Found on the street"
}

###

PUT http://localhost:3000/post/35785720-10de-4973-8606-465ba3df7e18
Content-Type: application/json

{
    "username": "CoolKid",
    "title": "Cat loves milk",
    "description": "If you love your cat let it drink milk!",
    "id": "35785720-10de-4973-8606-465ba3df7e18"
}

###

DELETE http://localhost:3000/post/35785720-10de-4973-8606-465ba3df7e18