GET http://localhost:3000/user

###

GET http://localhost:3000/user/626152f26dc07ba40c14e3b5

###

POST http://localhost:3000/user
 Content-Type: application/json

 {
     "username": "Åsna",
     "password": "hello"
 }

###

PUT http://localhost:3000/user/6261509d3e48f1cbb946d87c
Content-Type: application/json

{
    "username": "Åsna",
    "password": "123",
    "id": "6261509d3e48f1cbb946d87c"
}

###

DELETE http://localhost:3000/user/6261509d3e48f1cbb946d87c

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "Åsna",
    "password": "hello"
}

###

GET http://localhost:3000/user/login